name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: pooriaghaedi/go-container-action@master
        env:
          BACKENDTYPE: openai
          OAIKEY: ${{ secrets.OAIKEY }}
          KUBE_CONFIG : ${{secrets.KUBE_CONFIG}}


      - name: Check outputs
        run: |
          echo "{name}={value}" >> $GITHUB_OUTPUT
