name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: pooriaghaedi/go-container-action@master
        env:
          BACKENDTYPE: openai
          OAIKEY: ${{ secrets.OAIKEY }}
          K8SCONFIG: ${{ secrets.K8SCONFIG }}

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.myOutput }}"
