name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@master
      - name: Create Kube Config file
        run: |
            echo $KUBE_CONFIG > ~/.kube/config 
        shell: bash
        env:
          KUBE_CONFIG : ${{secrets.KUBE_CONFIG}}
          
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: pooriaghaedi/go-container-action@master
        env:
          BACKENDTYPE: openai
          OAIKEY: ${{ secrets.OAIKEY }}

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.myOutput }}"
