name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: K8sGPT
        id: K8sGPT
        # Put your action repo here
        uses: pooriaghaedi/go-container-action@master
        
        env:
          BACKENDTYPE: openai
          OAIKEY: ${{ secrets.OAIKEY }}
          KUBE_CONFIG : ${{secrets.KUBE_CONFIG}}
        

      - name: Check outputs
        run: |
          echo "${{ steps.K8sGPT.outputs.myOutput }}"

